theme = "gruvbox_dark_hard"

[editor]
line-number = "relative" 
gutters = ["line-numbers", "spacer", "diff", "diagnostics"]
completion-trigger-len = 1
bufferline = "always"
color-modes = true
auto-info = true
true-color = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.soft-wrap]
enable = true

[editor.statusline]
separator = "||"
left = ["mode", "spinner","file-type", "total-line-numbers"]
center =["diagnostics", "file-name", "spacer", "version-control"]
right = ["selections", "position", "file-encoding", "file-line-ending",]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tabpad = "all"

[editor.whitespace.characters]
tabpad = "."

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 1

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]